name: edtech-foundation-backend

on:
  push:
    branches:
      - main    
jobs:
 build-and-deploy:
  runs-on: ubuntu-latest
  steps:
    - name: checkout to repository
      uses: actions/checkout@v2
    - name: install and build
      run: npm ci
    - name: publish to registry
      uses: action/setup-node@v2
      with: 
        node-version: 18
        registry-url: 'https://npm.pkg.github.com'
        scope: '@natexian'
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
